default: &defaults
  hubzone_api_version:
    major: 1
    minor: 2
    patch: 0
    pre_release: alpha
  google_api_key: <%= ENV.fetch('HUBZONE_GOOGLE_API_KEY') { 'AIzaSyBsR78bM2H5vMlO60MAtaL9FVtPGWGyQ7c' } %>

production:
  <<: *defaults
  google_api_key: <%= ENV.fetch('HUBZONE_GOOGLE_API_KEY') { 'AIzaSyDZ4Pva7Z3dR-lPVLbgGqX8SXWgu3wvTEg' } %>

staging:
  <<: *defaults

demo:
  <<: *defaults

dev:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
